name: Cloudflare Pages

on:
    push:
        branches:
          - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: decode secrets Base64
        uses: akiojin/decode-base64-github-action@v0.1.0
        with:
            base64: ${{ secrets.ENV_BASE64 }}
            output-path: ./src/environments/environment.prod.ts
     
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build-prod
          cp -a dist/which-room-client/index.html dist/which-room-client/404.html
        env:
          CI: true
     
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "which-room"
          directory: "dist/which-room-client"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}